### PR TITLE
Improve how Jedi handles Numpy

### LINKED ISSUE #243: `Failed to load hook pylsp_completions: 'NoneType' object has no attribute 'type'` when working with Numpy 1.23
Hey,
I am currently getting the error `Failed to load hook pylsp_completions: 'NoneType' object has no attribute 'type'` when I import numpy and try to trigger autocompletion. I think as a result I don't receive any autocompletion options for numpy, but for any submodules such as `numpy.testing` this works again.
I am not sure how to debug this, any ideas are welcome. My pylsp version is `v1.4.1`, I am using neovim `v0.8.0-dev+595-g95c65a6b22`. As config option I pass
```lua
	pylsp = {
	    configurationSources = { "flake8" },
	    plugins = {
		pyflakes = {enabled = false},
		pylint = {enabled = false},
		yapf = {enabled = false},
		black = {enabled = true},
		flake8 = {enabled = true},
		pycodestyle = {enabled = false},
		mccabe = {enabled = false},
		pydocstyle = {enabled = true},
	    }
	}

```
to pylsp.

### PR DESCRIPTION
**Pull request by gav451**
The documentation of [jedi.settings.auto_import_modules](https://jedi.readthedocs.io/en/latest/docs/settings.html#dynamic-stuff) tells that jedi may handle numpy's module globals trickery better when importing numpy instead of parsing.  The example script below prints the documentation strings of one of numpy's universal functions as well as the numpy version:

``` python
#!/usr/bin/env python
import jedi, numpy

# The next setting enables jedi to find the documention string of ufuncs:
jedi.settings.auto_import_modules = ["numpy"]
# Find the documentation string of numpy.cosh by completing numpy.cos:
script = jedi.Script(code := "import numpy; numpy.cos", path="<string>")
print(script.complete(1, len(code))[1].docstring())
print(f"numpy version: {numpy.version.__version__}")
```

The pull request adds numpy to jedi's auto\_import\_modules and allows the user to modify the module list.  The patch fixes:
1. The display of those documentation strings of numpy's universal functions by Eglot and python-lsp-server is good enough for me (I am using this patch for more than a year for this reason).
2. The incompatibility of jedi/python-lsp-server with numpy-1.23.x (this is a bonus).

Fixes #243.

### CODE REVIEW

File: pylsp/config/schema.json [hunk 1]
```diff
@@ -87,6 +87,14 @@
       "uniqueItems": true,
       "description": "List of errors and warnings to enable."
     },
+    "pylsp.plugins.jedi.auto_import_modules": {
+      "type": "array",
+      "default": ["numpy", "gi"],
```
Comment (ccordoba12) [inline pylsp/config/schema.json]:
```suggestion
      "default": ["numpy"],
```

Why `gi` here? I think that's specific to Linux only, so we shouldn't include it by default here. Besides, you can easily add it from your client.

File: pylsp/workspace.py [hunk 2]
```diff
@@ -14,6 +14,8 @@
 
 log = logging.getLogger(__name__)
 
+DEFAULT_AUTO_IMPORT_MODULES = ["numpy", "gi"]
```
Comment (ccordoba12) [inline pylsp/workspace.py]:
```suggestion
DEFAULT_AUTO_IMPORT_MODULES = ["numpy"]
```

I don't think `gi` should be here either.

**Review by ccordoba12 — COMMENTED** [review]
Hey @gav451, thanks a lot for your contribution! Besides the two suggestions I left for you below, please also update our configuration file by running

    python scripts/jsonschema2md.py pylsp/config/schema.json CONFIGURATION.md

**Comment by gav451** [comment]
Hey @ccordoba12, I have amended my pull request taking into account your remarks.
It was not clear to me that you prefer that contributors have to update CONFIGURATION.md and you are right about removing "gi" (I had added "gi" because jedi has jedi.settings.auto_import_modules = ['gi'] by default leaving it open for discussion).

**Comment by ccordoba12** [comment]
Thanks @gav451! One last thing I forgot to mention before: could you remove the following constraint to see if our Numpy tests pass now?

https://github.com/python-lsp/python-lsp-server/blob/449d11a23f752e3134d3d8f93ba21ce760eeb964/pyproject.toml#L56

**Comment by gav451** [comment]
Thanks @ccordoba12 for your guidance (next time I know I have to do all development steps). I checked that the Numpy test passed before amending and force-pushing. See the short test summary below:
```
=========================== short test summary info ============================
FAILED test/plugins/test_flake8_lint.py::test_flake8_multiline - AssertionError: assert ['flake8', '-...,E,F,W,T4,B9'] == ['flake8', '-...h/...
============ 1 failed, 136 passed, 9 skipped, 7 warnings in 47.91s =============
```
I had also to install `yapf` and `whatthepatch` manually, since I did not succeed to edit the test section in `pyproject.toml` to do it automatically.

**Comment by ccordoba12** [comment]
> Thanks @ccordoba12 for your guidance

No problem, thanks a lot for a great contribution!

> I had also to install yapf and whatthepatch manually, since I did not succeed to edit the test section in pyproject.toml to do it automatically.

Yeah, you need to install pylsp with

    pip install python-lsp-server[all]

to get all its dependencies for testing.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @gav451!
