### ISSUE TITLE
`Failed to load hook pylsp_completions: 'NoneType' object has no attribute 'type'` when working with Numpy 1.23

### ISSUE THREAD

**Issue by jhossbach** [python-lsp/python-lsp-server#243]
Hey,
I am currently getting the error `Failed to load hook pylsp_completions: 'NoneType' object has no attribute 'type'` when I import numpy and try to trigger autocompletion. I think as a result I don't receive any autocompletion options for numpy, but for any submodules such as `numpy.testing` this works again.
I am not sure how to debug this, any ideas are welcome. My pylsp version is `v1.4.1`, I am using neovim `v0.8.0-dev+595-g95c65a6b22`. As config option I pass
```lua
	pylsp = {
	    configurationSources = { "flake8" },
	    plugins = {
		pyflakes = {enabled = false},
		pylint = {enabled = false},
		yapf = {enabled = false},
		black = {enabled = true},
		flake8 = {enabled = true},
		pycodestyle = {enabled = false},
		mccabe = {enabled = false},
		pydocstyle = {enabled = true},
	    }
	}

```
to pylsp.

**Comment by ccordoba12** [comment]
Hey @jhossbach, thanks for reporting. I guess you're using Numpy 1.23, right? If that's the case, please downgrade to 1.22 and try again. That should fix your problem for now.

**Comment by jhossbach** [comment]
This works indeed, may I ask why that is?

**Comment by ccordoba12** [comment]
We don't know yet. We just noticed that our tests started to fail as soon as Numpy 1.23 was released.

**Comment by jhossbach** [comment]
Hmm, that is weird indeed, thanks for the quick reply!

**Comment by ccordoba12** [comment]
Note: This is a bug in Jedi, see https://github.com/davidhalter/jedi/issues/1864.

**Comment by ccordoba12** [comment]
This will be solved in the next PyLSP version by directly importing Numpy to provide completions.
